spring.application.name=Pc2

# Conexión directa a tu base de datos PostgreSQL en la nube de Render
spring.datasource.url=jdbc:postgresql://dpg-d8c9rgmq1p3s73cn2o4g-a.oregon-postgres.render.com:5432/utpdb
spring.datasource.username=utpuser
spring.datasource.password=aht4FlWQfy72oQBREwllRiGDQvXLKamG

# Configuraciones obligatorias para el Dialecto de PostgreSQL 18 y Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.open-in-view=false
springdoc.swagger-ui.enabled=false
