spring.application.name=Pc2

# Conexión flexible: Lee las variables de Render, y si no existen (en tu PC), usa valores por defecto
spring.datasource.url=${DB_URL:jdbc:postgresql://dpg-d8c9rgmq1p3s73cn2o4g-a.oregon-postgres.render.com:5432/utpdb}
spring.datasource.username=${DB_USER:utpuser}
spring.datasource.password=${DB_PASSWORD:aht4FlWQfy72oQBREwllRiGDQvXLKamG}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuraciones obligatorias para el Dialecto de PostgreSQL y Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Configuración del puerto dinámico para Render
server.port=${SERVER_PORT:8080}

# Otras configuraciones
spring.jpa.open-in-view=false
springdoc.swagger-ui.enabled=false